# Generated by Django 5.2 on 2025-04-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diy_web_pp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
