# Generated by Django 5.2 on 2025-04-12 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diy_web_pp', '0006_item_itemimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_from', to='diy_web_pp.item')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_sent', to=settings.AUTH_USER_MODEL)),
                ('to_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_to', to='diy_web_pp.item')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('swap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='diy_web_pp.swaprequest')),
            ],
        ),
    ]
